# Site settings
name: ab_Chen	
email: purple-purple@outlook.com
author: ab_chen
url: 
resume_site: 
github: https://github.com/purple-purple/
baseurl:
description: Actually, less is more!
meta_description: 
motto:
banner:

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: purple-purple
highlighter: Pygments

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : null
    disqus :
        short_name : null
